devices([
  "iPhone 16 Pro Max",
  "iPhone 16",
  "iPad Pro (13-inch) (M4)"
])

languages(["en-US", "pt-BR"])

scheme(ENV["SCHEME"] || "App")

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)

override_status_bar(true)
